# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: 'default'
  vmImage: ubuntu-latest

steps:

- task: TerraformCLI@2
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/diwaacr'
    allowTelemetryCollection: false

- script: 
    cd $(System.DefaultWorkingDirectory)/diwaacr
    terraform import azurerm_container_registry.diwaacr /subscriptions/4d294b57-bde7-4a42-8c2c-db1c20f6be54/resourceGroups/aksdemocluster-rg/providers/Microsoft.ContainerRegistry/registries/diwakbunj
  displayName: 'terraform import'
  
- task: TerraformCLI@2
  displayName: Terraform validate
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/diwaacr'
    allowTelemetryCollection: false

- task: TerraformCLI@2
  displayName: Terraform plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/diwaacr'
    environmentServiceName: 'diwademoazure'
    allowTelemetryCollection: false

- task: TerraformCLI@2
  displayName: Terraform apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/diwaacr'
    environmentServiceName: 'diwademoazure'
    allowTelemetryCollection: true